### ISSUE TITLE
Load redirects in bulk

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#104]
@kyleschmolze, I think you said you could take care of this one.

I'd like to load in the 301 redirects from the old eastbaydsa.org URLs to the new (e.g. `/about-caucuses` to `/about/caucuses`). I can attach the final spreadsheet when the URL questions are all settled.

Right now, the outstanding questions are around #89 and #99 (specifying whether meeting minutes can be a separate blog and what the final format for event pages will be).

**Comment by wesholing** [comment]
Hey folks, here's the CSV with the redirects. I didn't include events, though. Those URLs are still TBD because they're dependent on event ID, and I'll need to revise the slugs in NationBuilder, so I can enter those manually as I go.
[eastbaydsa-redirects.zip](https://github.com/eastbaydsa/website/files/1935025/eastbaydsa-redirects.zip)

**Comment by kyleschmolze** [comment]
Ready to go! #108

**Comment by kyleschmolze** [comment]
Ok, this is done, @wesholing! All 239 redirects have been loaded in, view them here: https://eastbaydsa-website-staging.herokuapp.com/admin/redirects
