### ISSUE TITLE
Build a Join page

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#114]
Right now, the join page has many components:

1. A link to the nice "Renew" page someone put together: http://renew.eastbaydsa.org/
2. A link to the National DSA join page (https://act.dsausa.org/donate/membership/). 
3. A link to our events calendar
4. A form to sign up for our newsletter

Which of these are we trying to recreate? All of them? I feel that the most important aspect of the join page is to rope them into the local chapter, while explaining that they won't officially be a member until they join via national. But since there's a ~2 month delay between signing up for national and us knowing about it, I'd rather focus on getting them involved / subscribed asap, and officially signed up secondarily.

Thoughts?

**Comment by kyleschmolze** [comment]
Cool I'll just do a simple re-build, without changing much copy, so it's easy to green light. 

Should be able to PR it tmw

**Comment by sarmaswe** [comment]
Sounds good -- thanks, Kyle.

**Comment by kyleschmolze** [comment]
PR Submitted, would love feedback! #120
