### ISSUE TITLE
Proposed visual update

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#115]
Ok, I'd love for us to make some visual updates before launch, and I think we can launch with something closer to the design work in #4. The problem is that those designs don't fit our current data modeling, as pretty as they are. So I took a stab at a redesign of the current layout / page elements while keeping in mind our current backend, meaning that this design can be implemented *now* (and then upgraded over time). 

Would love a 👍, 👎, or written feedback from @dominic @wesholing and @sarmaswe!

Some aspects of this design:
- Only 2 font sizes in page content (a requirement of using the trix editor), but a more distinct title/subtitle layout
- Titles/Pages can be made to really stand out with background-images
- Consistent color sets with our logo, other DSA websites, and #4 (just standard red, purple, and greys)
- Uses the ManifoldDSA font! (Who made DSA a font??? Amazing.)
- Home page is rendered exactly like any other Page, but just includes next 3 upcoming events.
- Spacing between elements is extremely simple: 20px between most items (occassionally 10 or 30 when needed), 15px padding on link-cards, buttons are 50px tall, fixed-width single column page layout 700px wide.
- Easy scaling for responsive/mobile layouts

Design file: https://www.figma.com/file/Jx7z2peaJqHX54NTMv0wsV3h/EB-DSA

Screenshots:

<img width="1280" alt="group 4" src="https://user-images.githubusercontent.com/1200038/39960694-ecac5b72-55db-11e8-9b0e-508da4c7bfc2.png">

---

<img width="1280" alt="group 4feas" src="https://user-images.githubusercontent.com/1200038/39960701-20e4cdf2-55dc-11e8-84b5-53892cebd041.png">

---

<img width="1280" alt="fab s" src="https://user-images.githubusercontent.com/1200038/39960703-265e52e4-55dc-11e8-873a-a29e3d64e93d.png">

---

<img width="1280" alt="hbv" src="https://user-images.githubusercontent.com/1200038/39960704-287317a4-55dc-11e8-9687-b0dcb6926f4b.png">

---

<img width="1280" alt="ferabs" src="https://user-images.githubusercontent.com/1200038/39960707-2a6bf756-55dc-11e8-910a-bbeb20d486cc.png">

**Comment by sarmaswe** [comment]
Woah, I’m traveling and won’t have time to really look at these until
Monday, though at first glance, this looks great! And it looks like you’re
matching the existing content structure for the new site, which is 👍👍

Thank you, Kyle 🙂

(Hoping reply by email works as intended)

**Comment by dominic** [comment]
@kyleschmolze I am very :+1: on these changes to launch with. Some feedback:

- I think for mobile, we'll need to use a full hamburger menu (in case anyone adds a 5th item)
- I wanna make sure for our large width option, the logo and menu items are still bound to a max-width (layout of current navbar essentially, minus social links which is a good substraction)
- For homepage, I want to expand the events somehow, but we can get to that later. If something comes to mind, I say run with it.

Awesome iteration dude!
