### ISSUE TITLE
Widen calendar view

### ISSUE THREAD

**Issue by dominic** [eastbaydsa/website#121]
Since there's no line length concerns, let's let the calendar break out of the grid a little bit more so that events have more room:

<img width="971" alt="screen shot 2018-05-20 at 10 32 03 am" src="https://user-images.githubusercontent.com/185645/40281736-06fabe8a-5c1a-11e8-8f03-e9e9a2a2fc42.png">

**Comment by kyleschmolze** [comment]
I fixed this in #124 but I still think that on mobile this would ideally render completely differently (like just a list view basically)
