### ISSUE TITLE
COPY : homepage : convention passed

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#128]
@wesholing, should you revise copy or delete section on homepage about convention, as it already passed?   

screenshot below 
<img width="772" alt="screen shot 2018-05-23 at 4 03 54 pm" src="https://user-images.githubusercontent.com/13740788/40455677-ec0dc37a-5ea2-11e8-8112-a09a8cea47e1.png">

**Comment by wesholing** [comment]
Good catch. I've fixed it to reflect what's on the current home page.

Thanks!
Wes
