### ISSUE TITLE
Front-end framework?

### ISSUE THREAD

**Issue by nfiniteset** [eastbaydsa/website#13]
Should this website use any front-end framework? To what degree?

Some scenarios I can imagine:
- Use vanilla js (or transpiled ES6/ESFuturewhatever) for minimal front-end interactivity.
- Use jQuery for minimal front-end interactivity. 
- Use React/Angular/Vue for minimal interactivity.
- Use React/Angular/Vue for SPA backed by a Rails JSON API.

WFIW Rails 5.1 makes Webpack integration pretty straight forward. It's much much easier than it used to be.

I wonder about things like how much interactivity the app will have. I imaging most of it will be on the admin side in the page editor and other admin tools. On the user-side I expect see a few forms that we could submit via Ajax, but nothing major.

How should we be thinking about developer accessibility? jQuery may be a safe bet because every developer has likely done a little work with it. But the jQuery road leads to spaghetti. Frameworks provide more structure, but require more experience to be effective. I bet most of our professional devs have worked with at least one, but which one? Would any frameworks be appealing or a turn off to our volunteers?

**Comment by dominic** [comment]
Closing for now, but really open to folks picking this up as we build a more stable team.
