### ISSUE TITLE
LINKS : bottom nav : "Campaign" link not working 

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#130]
@wesholing, possible to update with a working link?
- In bottom navigation, “Campaign” link does not open anything

**Comment by wesholing** [comment]
These aren't working for me either, but the URLs for both are right. (I also can't change the Facebook link.)

@dominic or @kyleschmolze, can you take a look at this?

**Comment by kyleschmolze** [comment]
We had a Redirect from `/campaigns` to `/campaigns`, and it created a redirect loop. This should not be allowed, so I added a validation to prevent it from happening in the future, check the new PR

![image](https://user-images.githubusercontent.com/1200038/40498916-3ae6417e-5f35-11e8-87d0-39df3ecc1104.png)

**Comment by kyleschmolze** [comment]
(I also deleted that Redirect, so the campaign page works now)
