### ISSUE TITLE
Add more header levels to editor

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#141]
Can someone please add H4, H5, and H6 to the new visual editor? I don't usually need anything beyond H3s, but they come in handy when writing up the meeting notes for either sections within sections or when including some copy (in a motion, usually) that another member has submitted for consideration by the committee.

**Comment by kyleschmolze** [comment]
Right now, the H4, H5, and H6 all have the same styles as our normal paragraph tags:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1200038/41935897-3f969db6-7940-11e8-9515-763aae1d2076.png">

I don't particularly see a reason to add 3 new font styles in between 18px (normal) and 24px (H3), unless you think they need certain weight/color or other differentiators. What do you think the in between styles / font sizes should be?

**Comment by dominic** [comment]
Gonna close this in favor of a more detailed editor requirements spec.
