### ISSUE TITLE
Add "Add to Google Calendar" link

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#146]
I modified the event template a while back to auto-generate an "Add to Google Calendar" link to event pages. Could we keep that, too? It's basically just a dynamically generated URL string that pulls event data already on the page (but only if the necessary data is on the page).

**Comment by dominic** [comment]
:+1: 

Woud love to have this whole calendar be publicly subscribe-able too. Good stuff in https://www.toasterlovin.com/rails-webcal-links-with-icalendar-gem/
