### ISSUE TITLE
DESIGN : Homepage : Hero image (?)

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#158]
URL: https://www.eastbaydsa.org

So I'm liking that our homepage image is more specific to EBDSA, though it's tough for me that our homepage image is of people's backs, as it feels like an immediately unwelcoming visual. I acknowledge that it's difficult to find a good image for this page that will also accommodate the text across the middle. 

@wesholing who could I talk with to see about other images we have lying around? Maybe I can store them all in one place. 

Or can we try to articulate what we're looking for here, maybe a landscape shot of the East Bay with DSA signage, and then request that as people are going to events and canvassing, and see what comes back?

If no one else feels similarly, okay then :) 

@dominic @kyleschmolze @wesholing @llkats 

![screen shot 2018-07-07 at 9 25 01 pm](https://user-images.githubusercontent.com/13740788/42416772-a9a0d3da-822c-11e8-95f0-a7a46d4c14d1.png)

**Comment by wesholing** [comment]
We discussed this today at our meeting, and landed on this image because it avoids any identity and anonymity issues. Dominic had a good selection of images that aren't from behind, and I think we could use them, but we should clear it with the people in the image before we do.

**Comment by sarmaswe** [comment]
@dominic @kyleschmolze @llkats are you guys good with the hero image? I'm basically asking if I should drop it or start looking for pictures.

**Comment by llkats** [comment]
I don't have strong feelings about the background image; I think it does the job for now, but we could always be on the look out for better hero images.

I _do_ think that the header text is difficult to read. I can make a different issue if that's more appropriate but I tried mocking up a couple different ways to make the text easier to read:

![image](https://user-images.githubusercontent.com/578156/43362661-ee0fe2ee-92a4-11e8-9b46-c8ce9fa29ba2.png)
- adding a tint with a linear-gradient

![image](https://user-images.githubusercontent.com/578156/43362663-06f57fe4-92a5-11e8-9722-1c127980aede.png)
- adding a contrasting background color

**Comment by sarmaswe** [comment]
Cool -- thank you, @llkats ! I think you're right about the text being difficult to read. I like your first option, and I think dimming the image makes me more okay with it. 

@kyleschmolze @dominic @wesholing -- any thoughts?

**Comment by sarmaswe** [comment]
I like the purple one too, so let's move ahead with that. What's the next step for that?

And the different page styles seems to make sense.

**Comment by llkats** [comment]
@sarmaswe I added the background and merged it today! Please feel free to reopen this issue or make a new one if you have more feedback about the hero component.

**Comment by sarmaswe** [comment]
Thank you @llkats !! It looks great
