### ISSUE TITLE
Make 302 redirects 301 instead

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#162]
Our redirects currently use the temporary redirect, HTTP server code 302. Please use 301 (permanent) instead.

**Comment by wesholing** [comment]
I'd like the redirects we have to be 301s. We changed our URL structure
when we migrated CMSes, and we're not going back to the old one, so they
don't need to be temporary.

**Comment by eventualbuddha** [comment]
@kyleschmolze explained that there is a `Redirect` model that is used by `PageController` to handle redirecting old URLs to the new style. This is an easy fix, but I need to get the development environment set up first. I'll open a separate ticket about that.
