### ISSUE TITLE
Setup a seeds.rb file or .sql file with actual Pages from production

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#172]
Would be great for new developers to have some content to view when they launch the portal.

**Comment by tilgovi** [comment]
If anyone finds this, I was able to set up my local environment by running `heroku pg:pull -a eastbaydsa-staging postgresql-crystalline-38585 ebdsa-website`

**Comment by tnoff** [comment]
We have a db snapshot we can set folks up with, closing this
