### ISSUE TITLE
`NATION_NAME` and `NATION_API_TOKEN`

### ISSUE THREAD

**Issue by eventualbuddha** [eastbaydsa/website#173]
What should I use for these values? The README doesn't really cover it.

**Comment by kyleschmolze** [comment]
I will Slack it to you, but do you know of any good solutions for this issue? Maybe something as simple as an encrypted archive in the repo we share the password to verbally. But I'm sure there are good solutions to this.

**Comment by kyleschmolze** [comment]
Ah - you're not on Slack yet. I emailed your email listed on your github profile, just put that into a `.env` file in the root directory of the repo.

**Comment by dominic** [comment]
Just invited you to our Slack too.

**Comment by eventualbuddha** [comment]
Thanks, seems to work now.
