### ISSUE TITLE
FEEDBACK: Home page and website 

### ISSUE THREAD

**Issue by dominic** [eastbaydsa/website#178]
Based on feedback from the steering committee

- [x] Tag articles from the news section to be on the homepage, to promote fresh content, and highlight our campaign work
- [ ] Add preview images to each article in the news section
- [x] Add "Events", "Join DSA" (<- link to national) buttons to the bottom of the homepage
- [ ] Include recent Tweets on homepage (no RTs, no replies?)
- [x] Include Jovanka, Prop 10 content in home page content/improve campaign content overall

**Comment by dominic** [comment]
I'll be tackling some of this checklist today; let's make new issues and edit the above description with issue numbers when someone starts on on.

**Comment by kyleschmolze** [comment]
3 of these are already done, and the remaining 2 I split out into their own issues. Closing.
