### ISSUE TITLE
NEW FEATURE: Search within eastbaydsa.org

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#184]
So it would actually be super simple to add a search function within eastbaydsa.org, and I think that given how much content there is, hidden down below many page levels (including meeting minutes, etc), a search function would be *super* useful. 

Proposal: Add a search field on the footer of the website, right above the "About us" section. When submitted, it just send them to DuckDuckGo with an internal site search, like [this](https://duckduckgo.com/?q=site%3Aeastbaydsa.org+bylaws&t=ffab&ia=web).

Bonus: If our navbar can handle another icon, add a magnifying glass icon in the top right, which, when clicked, expands into a search field.

**Comment by kyleschmolze** [comment]
@dominic #199  should be ready for merge, no?

**Comment by dominic** [comment]
@kyleschmolze Agreed - merging and deploying.
