### ISSUE TITLE
Set up Rails-Settings

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#188]
For the long term health of our home grown CMS system, we should probably have some configurable settings within the GUI. If we ever hope to have other DSA chapters use our site, we'll need to avoid too much hardcoding, and instead start building some controls into the database through a `Setting` model of *some* sort. 

The [rails-settings-cached](https://github.com/huacnlee/rails-settings-cached) gem, or the [activeadmin_settings_cached](https://github.com/artofhuman/activeadmin_settings_cached) gem, might be a good start! For our first setting, let's make it so that you can disable the hard-coded home page @dominic built, cause not every DSA chapter would want our hard-coded homepage 😄

**Comment by dominic** [comment]
Merged!
