### ISSUE TITLE
NEW FEATURE: Include recent Tweets on homepage

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#196]
As per #178 

Include recent Tweets on homepage (no RTs, no replies?)

**Comment by themurph23** [comment]
![image](https://user-images.githubusercontent.com/3690500/48974067-9a0dda00-f002-11e8-8011-4af2f7df0191.png)


That's how it looks at https://eastbaydsa-staging.herokuapp.com/ in the footer.

Is that close to what you were thinking? I wasn't sure about where it should be located, on it's own page or something.

**Comment by dominic** [comment]
I think that look great :+1: We need to do a little responsive formatting for tablet and mobile sizes now – need a hand with that, or do you wanna take a stab at the CSS?

**Comment by themurph23** [comment]
Oh hmm, the mobile version looks okay, but I guess the tablet version is messed up. I'll take a stab at it.
