### ISSUE TITLE
Set up Heroku staging site

### ISSUE THREAD

**Issue by bcipriano** [eastbaydsa/website#20]
Set up the "staging" version of the site on Heroku, where we can push new releases to preview before they go fully live.

This will include a document and/or script for doing the push - not sure yet if it will be complex enough to warrant a script.

**Comment by bcipriano** [comment]
@dominic, guessing not but is there an existing Heroku account already? I can set the staging site up on the free tier for now.

**Comment by dominic** [comment]
We don't have a EBDSA account yet. If you want to set up a free app on your personal account, we can transfer it later no prob.

**Comment by dominic** [comment]
We don't have a EBDSA account yet. If you want to set up a free app on your personal account, we can transfer it later no prob.

**Comment by bcipriano** [comment]
Staging site is up, https://eastbaydsa-website-staging.herokuapp.com/

Instructions for deploying to Heroku are in the main [README](https://github.com/eastbaydsa/website/blob/main/README.md).
