### ISSUE TITLE
NEW FEATURE: Add id to RSVP section of event pages

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#201]
_via Andrew Richner_

Please add `id="rsvp"` to the RSVP `h2` on events pages so that we can link directly to them.

**Comment by eventualbuddha** [comment]
This is usually done with `<a name=“rsvp”>`, right? I’m sure you could implement a JavaScript scroll, but it’s probably better to just use the built-in browser features.

**Comment by eventualbuddha** [comment]
Huh, interesting. *grumble grumble* in my day *grumble grumble*

**Comment by wesholing** [comment]
Yeah, I feel like I find a "new" standards update every week.

Since this one seems pretty quick, could we have it in place by this
weekend? The Jovanka people want it when they link from events on her site
to ours. Thanks!
