### ISSUE TITLE
Redirect URLs with slash to URLs without slash

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#215]
Users who visit URLs with a trailing slash don't get automatically moved to those without a trailing slash (e.g. `/resources/` to `/resources`), which splits the link equity and duplicates it in the analytics.

Please redirect all traffic to pages with the slash to pages without the slash.

**Comment by themurph23** [comment]
I haven't figured out how to do this in rails yet, but I did find this:

https://www.getelevar.com/how-to/fix-duplicate-url-google-analytics/

**Comment by dominic** [comment]
Enforcing the trailing slash programmatically seems to be the easier variant here: https://coderwall.com/p/w_ilwg/dealing-with-trailing-slashes-in-rails-apps

**Comment by themurph23** [comment]
Made a pull request

**Comment by dominic** [comment]
Merged and deployed.
