### ISSUE TITLE
BUG "Sorry, that email is not on our member roll..."

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#219]
I can't get into the forum anymore... :( When I attempt to log in via Auth0, I get "Sorry, that email is not on our member roll". 

Oddly, I went into Auth0 as an admin, and pulled the URL and API key to manually check our little membership-confirmation API, and it works properly! Aka. this url shows me as "found":

https://eastbaydsa-prod.herokuapp.com/memberships/check/?email=kyletns@gmail.com&api_key=NOT_INCLUDED_HERE

This shows up as "found", and yet Auth0 is still not letting me in. This means that *our* server is returned that I *am* a member, but the Auth0 pre-hook is still failing. 

@dominic has anything changed significantly enough on our Auth0 setup that might explain this?

**Comment by eventualbuddha** [comment]
I also can't get in.

**Comment by kyleschmolze** [comment]
Ok, just trying to track this down a bit more.

We use this "Hosted Page" to render a custom error message if there is a problem logging in: https://manage.auth0.com/#/login_page

This is the line that overrides the error message:
```
customErrors.passwordless['lock.fallback'] = 'Sorry, that email is not on our member roll. Contact info@eastbaydsa.org for help.'
```

The default dictionary for those messages is here: https://github.com/auth0/lock/blob/master/src/i18n/en.js#L32

If I comment out the custom error code above on our hosted page, then the error just becomes "WE'RE SORRY, SOMETHING WENT WRONG". Not very helpful...

**Comment by kyleschmolze** [comment]
Ok fixed it! 

I don't know why, but our server started responding to Auth0 with 301 redirects, which the node `https` module doesn't follow through by default. I switched up our impolmentation on to use the `request` module, which does follow redirects, and it all seems to work now!

**Comment by dominic** [comment]
Ah ha. I can explain that! We made a change to URLs to help @wesholing's analytics, so all paths without a trailing slash redirect to one with a trailing slash (from https://github.com/eastbaydsa/website/pull/217)

Sorry that broke login, but great catch! If you update the URL in Auth0 to have a trailing slash, it won't get a redirect anymore, though this seems like an even more flexible solution :+1:
