### ISSUE TITLE
Improve onboarding

### ISSUE THREAD

**Issue by maxlapides** [eastbaydsa/website#241]
The onboarding process is currently not trivial, making it difficult to onboard new team members. Let's create a simple script that stands up the project on a new computer.

**Comment by hktouw** [comment]
Made a first pass at this here https://github.com/eastbaydsa/website/pull/242

I need to validate this on a machine without the app installed, so I left this as a draft PR for now. I plan on testing this on my work computer later this week.

The script only works on OSX atm. Will new team members have macs or other types of computers?

**Comment by maxlapides** [comment]
Woah, looking awesome! Thanks!

I'll bet most users will have Macs, but we may have some Windows users. We could just get it working for macOS now and then come back to it if we require Windows support?

**Comment by hktouw** [comment]
> We could just get it working for macOS now and then come back to it if we require Windows support?

Sounds good to me.

Just tested this on my work computer and everything works as expected. Going to do some clean up before I open the PR for review. Not necessary but if you know of someone available to test this out, it would be nice to have them pull down that branch and run the scripts.

**Comment by maxlapides** [comment]
I just tried it out on my machine and it worked flawlessly! My only question is what the easiest way is to take a Postgres dump and import that? But this is awesome :)

**Comment by hktouw** [comment]
Oh that would be a great thing to add. I forgot that that was a part of the setup process, so I didn't add it. It should be pretty straightforward to modify the script to include the postgres dump file. I can modify the PR to do so.

**Comment by hktouw** [comment]
@maxlapides My PR should be ready to review now. Who do I ping to get a review?

**Comment by maxlapides** [comment]
Let's ask @BrainScraps and @tilgovi to review! I'll also check it out :)

**Comment by BrainScraps** [comment]
Thanks, I'll take a look!
