### ISSUE TITLE
google calendar integration out of date

### ISSUE THREAD

**Issue by forthlightning** [eastbaydsa/website#268]
when I look on my google calendar, sometimes I see events that are deleted on the website calendar, or sometimes I dont see events which are on the wbesite calendar

**Comment by tnoff** [comment]
@forthlightning can you check to see if you're still seeing the issue? We just fixed a bug with the calendar sync that's probably related

**Comment by tnoff** [comment]
https://github.com/eastbaydsa/website/pull/278
