### ISSUE TITLE
Lock down S3 permissions with presigned URLs

### ISSUE THREAD

**Issue by bcipriano** [eastbaydsa/website#41]
This is a followup from #12.

S3 permissions on our test bucket are quite open - world writable and CORS is configured to allow from anywhere. We'll need to lock this down.

- Add backend method we can call from the admin page, which will read Heroku config to determine the appropriate S3 bucket, then return a presigned URL that can be used for upload.
- Remove world bucket permissions, presigned URLs take care of this.
- Set proper CORS config - test bucket should only allow from local devs and staging Heroku, prod bucket should only allow from prod Heroku.

**Comment by bcipriano** [comment]
Ok, this is now pushed to staging and S3 setup is complete for the staging bucket.

@dominic going to reassign this to you to give it a try - drag n drop on any field set up with a Trix editor. If it works feel free to close this out, if not let me know!

**Comment by bcipriano** [comment]
Oh yeah also - I set Heroku config on the staging site for `ADMIN_EMAIL` and `ADMIN_PASSWORD`, you can use those to log into the admin site for testing until we figure out auth a bit more.

**Comment by dominic** [comment]
Looks great!
