### ISSUE TITLE
Drive footer content with ActiveAdmin

### ISSUE THREAD

**Issue by bcipriano** [eastbaydsa/website#59]
Footer contents are static right now:

<img width="1216" alt="screen shot 2017-11-11 at 3 40 53 pm" src="https://user-images.githubusercontent.com/2013647/32694515-b9201920-c6f6-11e7-91f9-532f37f681b0.png">

- Add class for footer sections ("Get Involved", "Donate", etc.)
- Add class for menu items in each section ("Home", "Store", etc.)
- Add config for the footer text items - "About Us" and Copyright sections e.g.

**Comment by dominic** [comment]
Something like a "Site Settings" page might be good for this? https://github.com/artofhuman/activeadmin_settings_cached or a similar gem.
