### ISSUE TITLE
Integrate donation page

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#65]
A goal of the updated eastbaydsa.org is for it to be a full skin on top of NationBuilder. The donation page currently sits on NationBuilder, and it would be great to integrate the donation page with the rest of the new site. 

Please explore options/requirements for a new donation page. Some ideas mentioned were embedding PayPal or using a donor widget. 

Proposed deadline: Monday, March 26
Proposed launch date for new site: Sunday, April 15

**Comment by dominic** [comment]
cc @jeffomatic

**Comment by jeffomatic** [comment]
The donation widget itself is generated by a blackbox that NationBuilder provides, and hooks into a donation CRM, so we can't circumvent it and go directly to PayPal without investigating whether it's feasible to skip the CRM part.  I think there are limited styling options, but you might want to talk to Wes Holing and see what he knows. 

I've never actually dug into how much we're getting out of having NationBuilder sitting between the donors and our PayPal account, so we might be able to chuck it, but at this point I have no idea about how easy or hard that would be.

**Comment by dominic** [comment]
I was looking at something like https://donorbox.org as a potential replacement. It's got the cost of adding even more dependencies to our stack, but also seems like a pretty simple service.

**Comment by sarmaswe** [comment]
@jeffomatic @dominic @kyleschmolze -- what are you guys thinking is the best way to move forward with the replacement donation page? 

Maybe Dom's https://donorbox.org suggestion? Any feedback on that?

Would it work to decide on way forward by Saturday, 3/24, and have the new donation page working by Monday, 4/2?

**Comment by jeffomatic** [comment]
I would prefer that we carry forward with our existing donation setup until
there is time (likely not for the next 3-4 weeks) to figure out how to
integrate this into the bank account, etc. Sorry for the inconvenience.

One thing I will convey is that it’s very likely we may need to create a
_separate_ donation stream as part of our effort to comply with electoral
regulations. In which case, I’m totally down to try a new donation provider.

**Comment by dominic** [comment]
Cool. I agree with Jeff. For donations, we can send folks to `eastbaydsa.nationbuilder.com` easily enough as needed.

**Comment by sarmaswe** [comment]
Sounds good!

**Comment by kyleschmolze** [comment]
`https://eastbaydsa.nationbuilder.com/donate` currently redirects to `https://www.eastbaydsa.org/donate`, but I assume that will change?

**Comment by dominic** [comment]
It will once we remove the custom domain, yeah.

**Comment by kyleschmolze** [comment]
PR #76 handles this - we can now just add a Donate link to the footer with whatever URL we want, when we're ready.
