### ISSUE TITLE
Prep homepage design for April launch 

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#66]
Design goal for the homepage for April launch is an updated version of existing homepage. The new site will use the content/copy on existing site.

Dominic to prep this and share with team. 

Proposed schedule
March 14: Dominic shares homepage design with team
March 21: Homepage design finalized 
April 1: Site updated with homepage design 
April 15: Launch date

**Comment by dominic** [comment]
:+1: 

I'll post a design based on our various mockups here tomorrow.

**Comment by kyleschmolze** [comment]
cleanup
