### ISSUE TITLE
Homepage: simple, temporary design

### ISSUE THREAD

**Issue by dominic** [eastbaydsa/website#68]
Here's my suggestion for a simple homepage that mimics our current content:

![homepage-simple](https://user-images.githubusercontent.com/185645/37449057-209b17da-27e6-11e8-9462-975dcf1318e6.png)

The contents are:

- A free-text section that can be edited containing rough chapter info
- The next upcoming event from NationBuilder

cc @wesholing

**Comment by wesholing** [comment]
Looks good to me. :)

**Comment by sarmaswe** [comment]
Dom, I like this design. Thanks for prepping and sharing. 

Should the top navigation match the existing site?

<img width="1262" alt="screen shot 2018-03-21 at 11 01 48 am" src="https://user-images.githubusercontent.com/13740788/37728799-698dc35e-2cf8-11e8-8dab-889ac0fbd75d.png">

Seems like the EBDSA icon on the left would serve as "Home." 

Is "Blog" a replacement for "News"?

And then we're just missing "Resources," "Campaigns," "Donate," and "Join" -- can we go ahead and include these on this version too?

As far as bottom navigation, the existing site doesn't have much, just Twitter and Facebook. Should we mimic that, or include essentially the items top navigation on the bottom as well?

<img width="1257" alt="screen shot 2018-03-21 at 11 04 20 am" src="https://user-images.githubusercontent.com/13740788/37728808-72085a62-2cf8-11e8-94dd-7b67240687e1.png">

**Comment by sarmaswe** [comment]
@kyleschmolze @maxlapides -- through conversations with @wesholing , we decided to scale back the goals for the new homepage design for the April launch. It's now essentially a basic redesign of the existing homepage. 

If you have a moment, please review Dom's suggestion and share any feedback, by Saturday, March 24, if possible :) 

After this initial April launch, we'd like to build a more thorough redesign process that delivers a greater departure from the existing design, and includes input from EBDSA stakeholders. At that point, we'd be able to consider more extensive design feedback. 

cc @dominic

**Comment by sarmaswe** [comment]
@kyleschmolze -- here's some context on the navigation. Right now I'm thinking about this as a modification to the design, though should this be another issue instead?

@wesholing @dominic -- please revise/add as needed 

The goal for this April launch is only a minor improvement on the design of the existing site. This being the case, the navigation for the new site might exactly match the existing site. The design Dom shared here carried over the navigation from an earlier proposed design. This navigation does not include sections that are currently on the site, which introduces a new question of where to place that content. The top and bottom navigation are also more different than I’m used to seeing -- maybe they should be more symmetrical? 

I'm also not clear on the development work behind modifications to the navigation, or how it would affect Wes's URLs. 

I think once the navigation is finalized, then the design is basically final for the April launch. Anything else missing?

**Comment by dominic** [comment]
re: navigation, it's totally configurable in the UI. So, it's just content. Y'all can put whatever links you want there. I think the logo should be a replacement for the previous "Home" link yep.

**Comment by dominic** [comment]
The bottom navigation is already built (though we should probably move some of the links around, and remove "Store" since that's not gonna happen yet). Since it's designed and implemented, I don't really see a reason to cut it up unless folks feel strongly.

**Comment by sarmaswe** [comment]
@dominic when you say "cut it up," what do you mean? And thanks for providing all this info. 

@kyleschmolze do you have what you need to get started?

**Comment by dominic** [comment]
@sarmaswe I just mean I don't see a reason to change the design or content since it's already built to the new design spec from @wesholing and Mark. The main reason we cut scope on the homepage is that we hadn't built it yet.

**Comment by sarmaswe** [comment]
@dominic I think I'm more trying to clarify what should be in each navigation because there are differences between your design and @wesholing 's latest design, and differences between the existing site and the new site, and differences between the top and bottom navigation.  If you and Wes are good with a certain navigation, then I'm good with that too. Here's what I'm seeing:

**Simple homepage design above** 

Top navigation: "Home" (as icon) / "About" / "Events" / "Blog" (replacement for existing "News"?) 

**Wes's latest designs**

Top navigation: "Home" (as icon) / "Home" / "About" / "Events" / "Donate" / "Join"

Bottom navigation: 
Get Involved: "Home" / "About" / "Events" / "News" / "Resources" / "Campaigns" 
Donate: "Donate" / "Store" / "Join"
About Us: copy
Follow Us: Facebook / Twitter

**Comment by dominic** [comment]
Well, let's split em up:

- The top navigation in the design above is totally configurable. I think the questions you're asking are more content questions than design - we can add all the links we want. Personally, I don't think we need a text "Home" link in addition to the logo, but @wesholing might have a different opinion and he knows the content best.
- The bottom navigation you described as @wesholing's matches mine too so I'm :+1:.

The real design for the homepage is what's between the top and bottom navigation though. That's the part that's unimplemented and needs someone to work on it.

I don't think I saved the photoshop file to make an updated mock, but I'm also not sure anyone needs it for the top nav. @wesholing ?

**Comment by sarmaswe** [comment]
That sounds good, and agree on not needing the redundant Home. And you mean that you need development work to implement the homepage design, right? Would that be a good place for Kyle to start?

**Comment by dominic** [comment]
Yep! I think everything between the top and bottom navs here is the homepage design.

**Comment by sarmaswe** [comment]
lol okay. @kyleschmolze might you instead be available to implement the homepage design? It sounds like @wesholing will work out the navigation, so no need to focus on that at the moment
