### ISSUE TITLE
[Admin] Support page redirects

### ISSUE THREAD

**Issue by dominic** [eastbaydsa/website#69]
For migrating content from the old to the new site, we need to be able to redirect from old URLs to new pages. Here's one thought I had on that:

- Add a `redirect_from` text field to pages and blog posts
- Add a wildcard route to the Rails app that points to a controller handling redirects (`RedirectController`?)
  - In this controller, for any route requested, first check for a record with a matching `redirect_from` value, and redirect to it if one is found.
  - If no match is found, serve a 404 response.

**Comment by dominic** [comment]
@wesholing has asked that some pages do multiple redirects. Perhaps we can do a comma separate list in the text field, or provide it as a `has_many` relationship.

**Comment by dominic** [comment]
URLs for redirect https://docs.google.com/spreadsheets/d/195Sfselqu6G8tGOJ-MYSDane29thQjtqjOB18gCfBmw/edit?usp=sharing

**Comment by kyleschmolze** [comment]
Hm. Bummer that we have to support multiple redirects, I'd say the only responsible way to do that is to add a new model for Redirects, and just have a `redirect_from_path` and a `redirect_to_path`. Comma separation makes querying and debugging feel messy to me. 

I'm happy to tackle this, but I'd love to get an answer to #71 before I start

**Comment by dominic** [comment]
Answered #71. I think I agree re: a separate model to handle multiple redirects. At a glance, I don't actually see any duplicates in there... @wesholing, is that still a requirement?

**Comment by kyleschmolze** [comment]
All done - I made it a separate model just cause it's easy to imagine duplicates being needed later and it's ultimately a very simple model to manage. I even added click-tracking just so we know which redirects are still being used.

**Comment by wesholing** [comment]
Hey folks,

Thanks for looking into this. Just to be clear, the migration doc just
includes the new URLs for existing pages (e.g. /about-dsa -> /about/dsa).
There are also 143 redirects
<https://eastbaydsa.nationbuilder.com/admin/sites/1/legacy/redirects>
currently in place in NationBuilder that cover legacy links to the old
Squarespace site, changes to URLs for pages on the current NationBuilder
site, and other contingencies that have come up while managing content. I
don't know how many redirects end up having the same destination URL, but
this is what I was thinking of when I raised the issue. If it's a manual
process to add these, just let me know and I can make it part of my content
migration work.

Thanks,
Wes

**Comment by kyleschmolze** [comment]
Yes, it'll be a manual process to migrate them over, if you could include that in your process that'd be great. The code is written but you'll need to wait for a merge and a release to start the content migration. Also if you have a spreadsheet of the 140+ I would be happy to write a script to import them.

**Comment by wesholing** [comment]
Terrific, thanks. NationBuilder lists them out as a table, so it should be
easy for me to copy them into a spreadsheet for you. I'll take care of that
once I finish the content migration here in the next couple days or so.

Wes
