### ISSUE TITLE
Should the footer links also be managed with Menu Items?

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#73]
Unless we want the footer to be completely static, it should probably also be managed by `MenuItem` objects as well, right? My suggestion is just that we merge the "Donate" and "Get Involved" columns into 1 column for footer links, and then we make it so that `MenuItems` can be tagged as belonging to the header or the footer, which means we can easily read out all the links for the header and also all the links for the footer.

**Comment by kyleschmolze** [comment]
This could be a way to solve #59

**Comment by dominic** [comment]
@kyleschmolze :+1: I like that a lot. Knocking out the donate column and just tracking two lists seems great.
