### ISSUE TITLE
Background images on Pages

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#74]
If we want pages to be able to have nice big fancy background images (which everyone does now, and yes, it looks great), all we'd need to do is:

- [ ] Copy the image upload code over from `Homes` to `Pages` so that we can attach images to Pages
- [ ] Come up with a default design for when there is no attached image
- [ ] Come up with a design for when there is an attached image (Should the text always be white over every image? Should that be configurable? What about adding a dark-overlay on images so that white text is always readable? Should *that* be configurable?)

**Comment by dominic** [comment]
:+1: 

Supporting it for pages should be as simple as adding a `featured_image_url` column. Uploads should be handled universally already.

**Comment by kyleschmolze** [comment]
Handled by #119
