### ISSUE TITLE
Why are Homes different from Pages?

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#75]
Since the "homepage" layout is almost the exact same as the Page layout, but it simply renders the next upcoming event at the bottom, is there any particular reason that `Homes` are different object types than `Pages`? It just seems a bit superfluous/confusing to have them be different. 

Especially since we'll be adding more layout options like background images, sub-pages, etc, it feels silly to have to build those things twice: once for pages and once for homepages.

I can think of a couple ways we could merge them:

- The homepage could be a special case of a Page which has the slug `""`.
- We could add a boolean "homepage" column on Pages, and the system would always pull the first Page for which `homepage == true` to use as the homepage.

**Comment by dominic** [comment]
@kyleschmolze This was from a world where the home page had a _much_ more distinct design, and would probably be a pretty long collection of custom fields. Essentially, `Homes` was gonna be a singleton model.

The only customization on the homepage now is pulling the most recent event from NationBuilder. We can have it render a custom template for the controller action `home`, or if `homepage == true` that accomplishes that. Reducing complexity and removing that model and admin tab sounds great for now.

**Comment by kyleschmolze** [comment]
Great, thanks for the context. If you think there's a good chance we'll get to that world in the near future, I'm happy to leave it for now - but if you're not sure then I may simplify :)

**Comment by dominic** [comment]
Okay! Since it's working now, let's leave it. We can probably tune the admin interface to make it less weird.

**Comment by kyleschmolze** [comment]
Handled by #119
