### ISSUE TITLE
Add margin space after list items

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#81]
The items in ordered lists and unordered lists are tight together compared with the spacing between paragraphs and other page elements. Please add a margin-bottom property to li elements. Maybe 0.3em?

Also, the line-height for li elements is equal to 1, but other page elements are greater. Perhaps this could be something like 1.3?

**Comment by wesholing** [comment]
Actually, it looks like the CSS declaration that sets the line-height also sets it for heading elements (h1, h2, etc.), and those could use the same increase. Let's try just changing the value for that instead of adding one just for list items.

**Comment by dominic** [comment]
Fixed by https://github.com/eastbaydsa/website/commit/8be52e239d9aa5b770826bd6c7f34f21e50ade87 too
