### ISSUE TITLE
Blog posts: add individual post display

### ISSUE THREAD

**Issue by dominic** [eastbaydsa/website#9]
Implement `BlogPostsController#show` to render an individual post's content at its given slug.

**Comment by bcipriano** [comment]
Seems like this is done already?

I see https://github.com/eastbaydsa/website/blob/127bf324abe275f31cfad189009cc039cc61a785/app/controllers/blog_posts_controller.rb#L8, and going to `/blog/<slug>` seems to work.

**Comment by dominic** [comment]
I'm going to do some more work on formatting and layout today and then I'll close it 👍
