### ISSUE TITLE
Build form pages

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#96]
Here are all of the non-static pages on the NationBuilder site that I couldn't create as part of the content migration. (This might need to be separate issues.) Depending on existing plans, you may already know about all of these, but I'm listing them here just in case.

https://www.eastbaydsa.org/campaigns-electoral-volunteer
New URL: https://www.eastbaydsa.org/campaigns/electoral/volunteer
Purpose: Collect list of interested members and non-members to work on endorsed candidates (currently Jovanka and Gayle, but would also include others in the future)
Notes: Tag entries with `interest_electoral`; include same fields as on current page. We will probably end up doing this for other campaigns, too, like healthcare and housing.

https://www.eastbaydsa.org/donate-once
New URL: https://www.eastbaydsa.org/donate/once
Purpose: Collect one-time donations to East Bay DSA
Notes: NationBuilder doesn't allow a single page to collect both one-time and recurring donations so we had to split them up. Dominic mentioned that we'll have to link to the existing NationBuilder page for this, but will that change in the future?

https://www.eastbaydsa.org/donate-recurring
New URL: https://www.eastbaydsa.org/donate/recurring
Purpose: Collect recurring donations to East Bay DSA
Notes: Same as previous page

https://www.eastbaydsa.org/join
New URL: (same)
Purpose: Get users to sign up for the newsletter
Notes: Since actual prospective members have to join national and can't join DSA in general or East Bay DSA in particular through our website, this was the best we can do. The form doesn't have to be on the join page, but there wasn't much reason to separate them.

**Comment by kyleschmolze** [comment]
If you want pages to be able to include forms, I don't know how we could easily do that in the next couple days. Only solution I see is to use Google Forms, and add a big button or link on the page to get there. MAYBE we could easily embed the google forms in a page, but even that goes beyond the abilities of Pages right now.

**Comment by kyleschmolze** [comment]
@wesholing are we cool with email-field-only forms? That's what we've got right now, which seems sufficient for launch to me, but let me know if not. 

As for donations, that's being handled in #65, so I'm going to close this.

Note: We don't currently have pages for https://eastbaydsa-website-staging.herokuapp.com/campaigns/electoral/volunteer nor https://eastbaydsa-website-staging.herokuapp.com/join
